### ISSUE TITLE
srt instead of str

### ISSUE THREAD

**Issue by colemar** [frgt10/dvdremuxer#1]
$ ./dvd-remuxer -h
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
...
...
  File "....../dvd_remuxer/dvdremux.py", line 277, in DVDRemuxer
    def _fix_vobsub_lang_id(self, idx_file: Path, langcode: srt):
NameError: name 'srt' is not defined. Did you mean: 'set'?

**Fix**: str not srt

**Comment by frgt10** [comment]
@colemar thanks for the bug report!
